dependencies:
  - ca-certificates=2021.5.30=h5b45459_0
  - certifi=2021.5.30=py37h03978a9_0
  - cycler=0.10.0=py_2
  - discretize=0.7.0=py37h0a3528d_0
  - empymod=2.1.2=pyhd8ed1ab_1
  - freetype=2.10.4=h546665d_1
  - future=0.18.2=py37h03978a9_3
  - geoana=0.1.1=py37h8c56517_0
  - icu=68.1=h0e60522_0
  - intel-openmp=2021.3.0=h57928b3_3372
  - jbig=2.1=h8d14728_2003
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h8ffe710_0
  - kiwisolver=1.3.1=py37h8c56517_1
  - lcms2=2.12=h2a16943_0
  - lerc=2.2.1=h0e60522_0
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libclang=11.1.0=default_h5c34c98_1
  - libdeflate=1.7=h8ffe710_5
  - liblapack=3.9.0=8_mkl
  - libpng=1.6.37=h1d00b33_2
  - libtiff=4.3.0=h0c97f57_1
  - llvmlite=0.36.0=py37habb0c8c_0
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-base=3.4.2=py37h0d1fb12_0
  - mkl=2020.4=hb70f87d_311
  - msys2-conda-epoch=20160418=1
  - numba=0.53.1=py37h9690626_1
  - numpy=1.21.1=py37hcbcd69c_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1k=h8ffe710_0
  - pandas=1.3.1=py37h90003fb_0
  - pillow=8.3.1=py37hd7d9ad0_0
  - pip=21.2.2=pyhd8ed1ab_0
  - properties=0.6.1=py_0
  - pymatsolver=0.1.3=pyhd8ed1ab_0
  - pymkl=0.0.3=py_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h03978a9_7
  - pyqt-impl=5.12.3=py37hf2a7229_7
  - pyqt5-sip=4.19.18=py37hf2a7229_7
  - pyqtchart=5.12=py37hf2a7229_7
  - pyqtwebengine=5.12.1=py37hf2a7229_7
  - python=3.7.10=h7840368_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytz=2021.1=pyhd8ed1ab_0
  - qt=5.12.9=h5909a2a_4
  - scikit-learn=0.24.2=py37h8ded0a9_0
  - scipy=1.7.0=py37h924764e_0
  - setuptools=49.6.0=py37h03978a9_3
  - simpeg=0.15.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h8ffe710_0
  - threadpoolctl=2.2.0=pyh8a188c0_0
  - tk=8.6.10=h8ffe710_1
  - tornado=6.1=py37hcc03f2d_1
  - ucrt=10.0.20348.0=h57928b3_0
  - utm=0.7.0=pyhd8ed1ab_0
  - vc=14.2=hb210afc_5
  - vectormath=0.2.2=py_0
  - vs2015_runtime=14.29.30037=h902a5da_5
  - wheel=0.36.2=pyhd3deb0d_0
  - wincertstore=0.2=py37h03978a9_1006
  - xz=5.2.5=h62dcd97_1
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.5.0=h6255e5f_0
